namespace ChefKnife.Display.WebAPI.DTOs;

public class MetDocument
{
    public string ObjectNumber { get; set; }
    public bool? IsHighlight { get; set; }
    public bool? IsTimelineWork { get; set; }
    public bool? IsPublicDomain { get; set; }
    public string ObjectId { get; set; }
    public string GalleryNumber { get; set; }
    public string Department { get; set; }
    public int? AccessionYear { get; set; }
    public string ObjectName { get; set; }
    public string Title { get; set; }
    public string Culture { get; set; }
    public string Period { get; set; }
    public string Dynasty { get; set; }
    public string Reign { get; set; }
    public string Portfolio { get; set; }
    public string ConstituentId { get; set; }
    public string ArtistRole { get; set; }
    public string ArtistPrefix { get; set; }
    public string ArtistDisplayName { get; set; }
    public string ArtistDisplayBio { get; set; }
    public string ArtistSuffix { get; set; }
    public string ArtistAlphaSort { get; set; }
    public string ArtistNationality { get; set; }
    public int? ArtistBeginDate { get; set; }
    public int? ArtistEndDate { get; set; }
    public string ArtistGender { get; set; }
    public string ArtistULANUrl { get; set; }
    public string ArtistWikidataUrl { get; set; }
    public string ObjectDate { get; set; }
    public int? ObjectBeginDate { get; set; }
    public int? ObjectEndDate { get; set; }
    public string Medium { get; set; }
    public string Dimensions { get; set; }
    public string CreditLine { get; set; }
    public string GeographyType { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string County { get; set; }
    public string Country { get; set; }
    public string Region { get; set; }
    public string Subregion { get; set; }
    public string Locale { get; set; }
    public string Locus { get; set; }
    public string Excavation { get; set; }
    public string River { get; set; }
    public string Classification { get; set; }
    public string RightsAndReproduction { get; set; }
    public string LinkResource { get; set; }
    public string ObjectWikidataUrl { get; set; }
    public DateTime? MetadataDate { get; set; }
    public string Repository { get; set; }
    public string Tags { get; set; }
    public string TagsAatUrl { get; set; }
    public string TagsWikidataUrl { get; set; }
}
